name: Build Maven Spring Boot Application

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
      build_args:
        description: 'Additional build arguments'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install ${{ github.event.inputs.build_args }}
